#!/bin/sh

OVERRIDE_DIR=/etc/systemd/system/seedsync.service.d
OVERRIDE_FILE=override.conf


#!/bin/sh -e

# Source debconf library.
. /usr/share/debconf/confmodule

db_get seedsync/username
USER=$RET

if [ -z "${USER}" ]; then
    echo "Skipping user override"
else
    echo "Setting user to ${USER}"

    if [ "$RET" = "root" ]; then
        rm -rf ${OVERRIDE_DIR}/${OVERRIDE_FILE}
    else
        mkdir -p ${OVERRIDE_DIR}
        echo [Service]\\nUser=${USER}\\nEnvironment=\"HOME=/home/${USER}\" > ${OVERRIDE_DIR}/${OVERRIDE_FILE}
    fi
fi

#DEBHELPER#
